#!/usr/bin/env bash
# Regenerate every verifier-fingerprint fixture family from pinned public sources, and
# diff the results against the committed artifacts.
#
# The honest families (SingleAction, MultiAction) are captures of accepting runs of the
# deployed verifier and are regenerated by CI from the pristine release pins
# (fixtures.yml). The random match-only families are produced by the same pipeline
# *plus* the capture tooling on the public `fingerprint-random-capture` branches of
# ebfull/halo2 and ebfull/orchard (a match-only exporter mode in halo2_proofs, and
# fabricate→replay random-capture drivers in orchard). Each branch is exactly one
# commit atop the corresponding release pin — asserted below. This script proves both
# claims at once:
#
#   1. the honest fixtures regenerated under the capture-branch toolchain are
#      byte-identical to the committed ones — the capture tooling demonstrably does
#      not disturb the existing pipeline; and
#   2. the random fixtures are reproducible from pinned public sources alone.
#
# Sources are cloned from the public forks at the pinned commits; set HALO2_SRC and/or
# ORCHARD_SRC to local checkout paths to clone from those instead (fully offline).
# Set REGEN_WORK_DIR to keep/reuse the build tree across runs (much faster); it is
# reset hard to the pinned commits each run. Random-family artifacts that are not yet
# committed are copied to REGEN_OUT_DIR (default scripts/generated/, gitignored).
#
# The one divergence from the CI regeneration environment: orchard's committed
# Cargo.lock pins halo2_proofs 0.3.4 from crates.io, so the capture branch's
# halo2_proofs is wired in via a [patch.crates-io] path override plus `cargo update
# --package halo2_proofs`. The script asserts the resulting lockfile delta is *exactly*
# the removal of that one package's registry source+checksum lines (version and the
# entire transitive dependency set unchanged); every subsequent cargo invocation runs
# --locked. See fixture-provenance-notes.md.
#
# Run from anywhere; exits non-zero on any violation.
set -euo pipefail
cd "$(dirname "$0")/.."

# The `fingerprint-random-capture` branch heads (the capture tooling), each exactly one
# commit atop the release pin used by CI's honest regeneration (fixtures.yml).
HALO2_COMMIT=7ef444fe1e5740838bf7aaaa5858e54e5edf3e64   # ebfull/halo2 fingerprint-random-capture
ORCHARD_COMMIT=cec7031f4cf1cd1e38d8e2961b569fd47676a9f5 # ebfull/orchard fingerprint-random-capture
HALO2_BASE_COMMIT=c12e83c4854aaa841bfd2ebc2451936a15a1cfb3   # zcash/halo2 release/halo2_proofs-0.3.4
ORCHARD_BASE_COMMIT=ae3511076ec8ecb39ffc02d9cdaf19c441c5b53d # zcash/orchard tag 0.15.3
HALO2_URL=${HALO2_SRC:-https://github.com/ebfull/halo2.git}
ORCHARD_URL=${ORCHARD_SRC:-https://github.com/ebfull/orchard.git}
HALO2_LOCK_CHECKSUM=5f63a999d9223fa9d3b9db3031fedc316e6039a0ae0f67394408b16ef670c69f

REPO_ROOT=$PWD
OUT_DIR=${REGEN_OUT_DIR:-scripts/generated}

if [[ -n "${REGEN_WORK_DIR:-}" ]]; then
  WORK_DIR=$REGEN_WORK_DIR
  mkdir -p "$WORK_DIR"
else
  WORK_DIR=$(mktemp -d)
  trap 'rm -rf "$WORK_DIR"' EXIT
fi

# Clone (or reuse) a source tree and force it to exactly the pinned capture-branch
# commit, asserting the branch provenance: exactly one commit atop the release pin.
# `git clean` keeps target/ so a reused REGEN_WORK_DIR stays warm.
prepare_source() {
  local name=$1 url=$2 commit=$3 base=$4
  local dest="$WORK_DIR/$name"
  if [[ ! -d "$dest/.git" ]]; then
    echo "Cloning $name from $url"
    git clone --quiet "$url" "$dest"
  fi
  if ! git -C "$dest" cat-file -e "${commit}^{commit}" 2>/dev/null; then
    git -C "$dest" fetch --quiet origin
  fi
  git -C "$dest" checkout --quiet --detach "$commit"
  git -C "$dest" reset --hard --quiet "$commit"
  git -C "$dest" clean -fdxq --exclude=target
  if [[ "$(git -C "$dest" rev-parse HEAD)" != "$commit" ]]; then
    echo "VIOLATION: $name is not at pinned commit $commit" >&2
    exit 1
  fi
  if [[ "$(git -C "$dest" rev-parse HEAD^)" != "$base" ]]; then
    echo "VIOLATION: $name capture commit is not exactly one commit atop its release pin $base" >&2
    exit 1
  fi
  if [[ -n "$(git -C "$dest" status --porcelain)" ]]; then
    echo "VIOLATION: $name working tree is not clean at the pinned commit" >&2
    exit 1
  fi
}

prepare_source halo2 "$HALO2_URL" "$HALO2_COMMIT" "$HALO2_BASE_COMMIT"
prepare_source orchard "$ORCHARD_URL" "$ORCHARD_COMMIT" "$ORCHARD_BASE_COMMIT"

# Wire the capture branch's halo2_proofs into orchard (see the header comment) and
# assert the lockfile delta is exactly the one package's registry source+checksum
# removal.
printf '\n[patch.crates-io]\nhalo2_proofs = { path = "../halo2/halo2_proofs" }\n' \
  >> "$WORK_DIR/orchard/Cargo.toml"
(cd "$WORK_DIR/orchard" && cargo update --quiet --package halo2_proofs)
lock_delta=$(git -C "$WORK_DIR/orchard" diff -U0 -- Cargo.lock | grep -E '^[+-][^+-]' || true)
expected_delta='-source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "'"$HALO2_LOCK_CHECKSUM"'"'
if [[ "$lock_delta" != "$expected_delta" ]]; then
  echo "VIOLATION: unexpected Cargo.lock delta after the halo2_proofs path override:" >&2
  git -C "$WORK_DIR/orchard" diff -- Cargo.lock >&2
  exit 1
fi
echo "Cargo.lock delta is exactly the halo2_proofs registry source+checksum removal."

# Install orchard's pinned toolchain (mirrors fixtures.yml), then run every capture
# driver in one pass. The unanchored filter matches the two honest and three random
# drivers, and deliberately not the Rust-only rejected:: capture.
if command -v rustup >/dev/null 2>&1; then
  (cd "$WORK_DIR/orchard" && rustup show >/dev/null)
fi
mkdir -p "$WORK_DIR/out"
(
  cd "$WORK_DIR/orchard" &&
    env ORCHARD_LEAN_SINGLE_FIXTURE_OUT="$WORK_DIR/out/SingleAction.Fixture.lean" \
      ORCHARD_LEAN_MULTI_FIXTURE_OUT="$WORK_DIR/out/MultiAction.Fixture.lean" \
      ORCHARD_LEAN_SINGLE_RANDOM_FIXTURE_OUT="$WORK_DIR/out/SingleActionRandom.Fixture.lean" \
      ORCHARD_LEAN_MULTI_RANDOM_FIXTURE_OUT="$WORK_DIR/out/MultiActionRandom.Fixture.lean" \
      ORCHARD_LEAN_TRIPLE_RANDOM_FIXTURE_OUT="$WORK_DIR/out/TripleActionRandom.Fixture.lean" \
      ORCHARD_LEAN_SINGLE_RANDOM_PROOF_OUT="$WORK_DIR/out/SingleActionRandom.proof-bytes.hex" \
      ORCHARD_LEAN_MULTI_RANDOM_PROOF_OUT="$WORK_DIR/out/MultiActionRandom.proof-bytes.hex" \
      ORCHARD_LEAN_TRIPLE_RANDOM_PROOF_OUT="$WORK_DIR/out/TripleActionRandom.proof-bytes.hex" \
      cargo test --locked --lib --features verifier-fingerprint \
      circuit::fingerprint::fingerprint_capture -- --nocapture
)

# generated-file : committed-path : requirement
# "required": the committed file must exist and match byte-for-byte (the honest
# families; failure means the capture tooling disturbed the pipeline or the pins
# drifted).
# "optional": match if committed, otherwise stash in $OUT_DIR.
pairs=(
  "SingleAction.Fixture.lean:Zcash/Snark/Fixtures/SingleAction/Fixture.lean:required"
  "MultiAction.Fixture.lean:Zcash/Snark/Fixtures/MultiAction/Fixture.lean:required"
  "SingleActionRandom.Fixture.lean:Zcash/Snark/Fixtures/SingleActionRandom/Fixture.lean:optional"
  "MultiActionRandom.Fixture.lean:Zcash/Snark/Fixtures/MultiActionRandom/Fixture.lean:optional"
  "TripleActionRandom.Fixture.lean:Zcash/Snark/Fixtures/TripleActionRandom/Fixture.lean:optional"
  "SingleActionRandom.proof-bytes.hex:Zcash/Snark/Fixtures/SingleActionRandom/proof-bytes.hex:optional"
  "MultiActionRandom.proof-bytes.hex:Zcash/Snark/Fixtures/MultiActionRandom/proof-bytes.hex:optional"
  "TripleActionRandom.proof-bytes.hex:Zcash/Snark/Fixtures/TripleActionRandom/proof-bytes.hex:optional"
)

status=0
stashed=0
for pair in "${pairs[@]}"; do
  generated="$WORK_DIR/out/${pair%%:*}"
  rest=${pair#*:}
  committed=${rest%%:*}
  requirement=${rest#*:}
  if [[ ! -f "$generated" ]]; then
    echo "VIOLATION: capture run did not produce $generated" >&2
    status=1
    continue
  fi
  if [[ -f "$committed" ]]; then
    if cmp -s "$generated" "$committed"; then
      echo "OK: $committed matches the regenerated capture byte-for-byte."
    else
      echo "VIOLATION: $committed differs from the regenerated capture ($generated)" >&2
      status=1
    fi
  elif [[ "$requirement" == "required" ]]; then
    echo "VIOLATION: committed fixture $committed is missing" >&2
    status=1
  else
    mkdir -p "$OUT_DIR"
    cp "$generated" "$OUT_DIR/${pair%%:*}"
    echo "Generated, not yet committed: $OUT_DIR/${pair%%:*}"
    stashed=$((stashed + 1))
  fi
done

if [[ $status -eq 0 ]]; then
  echo "fingerprint fixtures: all committed artifacts match; ${stashed} pending artifact(s) stashed in $OUT_DIR."
fi
exit $status
